"""Super Admin — AI Social Module.

GET  /api/admin/social/models
POST /api/admin/social/ai-config
POST /api/admin/social/force-generate
GET  /api/admin/social/tenant-overview
"""
from __future__ import annotations

from typing import Any, Optional

from datetime import datetime, timezone

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.dependencies import SuperAdmin
from app.modules.social.models import (
    SocialBrandIdentity,
    SocialContentDraft,
    SocialPostingPreferences,
    SocialSampleUploads,
    SocialApprovalQueue,
    SocialScheduleQueue,
)
from app.modules.tenants.models import Tenant

router = APIRouter(prefix="/api/admin/social", tags=["Admin — AI Social"])

# In-memory AI config (extend to DB-backed in production)
_ai_config: dict[str, Any] = {
    "model": "gpt-4o",
    "max_drafts_per_run": 5,
    "auto_approve": False,
    "default_tone": "professional",
    "enabled_platforms": ["FB", "IG", "TIKTOK", "TWITTER"],
}


# ── Schemas ────────────────────────────────────────────────────────────────

class AiConfigIn(BaseModel):
    model: Optional[str] = None
    max_drafts_per_run: Optional[int] = None
    auto_approve: Optional[bool] = None
    default_tone: Optional[str] = None
    enabled_platforms: Optional[list[str]] = None


class ForceGenerateIn(BaseModel):
    tenant_id: str
    count: int = 3
    topic_hints: Optional[list[str]] = None


# ── Endpoints ──────────────────────────────────────────────────────────────

@router.get("/models")
async def get_social_models(
    _: SuperAdmin,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Return counts across all AI Social tables."""
    brand_count = (await db.execute(select(func.count()).select_from(SocialBrandIdentity))).scalar_one()
    draft_count = (await db.execute(select(func.count()).select_from(SocialContentDraft))).scalar_one()
    upload_count = (await db.execute(select(func.count()).select_from(SocialSampleUploads))).scalar_one()
    prefs_count = (await db.execute(select(func.count()).select_from(SocialPostingPreferences))).scalar_one()
    approval_count = (await db.execute(select(func.count()).select_from(SocialApprovalQueue))).scalar_one()
    schedule_count = (await db.execute(select(func.count()).select_from(SocialScheduleQueue))).scalar_one()

    return {
        "models": {
            "social_brand_identities": brand_count,
            "social_content_drafts": draft_count,
            "social_sample_uploads": upload_count,
            "social_posting_preferences": prefs_count,
            "social_approval_queue": approval_count,
            "social_schedule_queue": schedule_count,
        }
    }


@router.post("/ai-config")
async def set_ai_config(
    body: AiConfigIn,
    _: SuperAdmin,
) -> dict[str, Any]:
    """Update the global AI Social generation config."""
    if body.model is not None:
        _ai_config["model"] = body.model
    if body.max_drafts_per_run is not None:
        _ai_config["max_drafts_per_run"] = body.max_drafts_per_run
    if body.auto_approve is not None:
        _ai_config["auto_approve"] = body.auto_approve
    if body.default_tone is not None:
        _ai_config["default_tone"] = body.default_tone
    if body.enabled_platforms is not None:
        _ai_config["enabled_platforms"] = body.enabled_platforms
    return {"ok": True, "config": _ai_config}


@router.post("/force-generate")
async def force_generate(
    body: ForceGenerateIn,
    _: SuperAdmin,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Force-generate drafts for a specific tenant (admin override)."""
    import uuid as _uuid
    from app.modules.social.models import SocialContentDraft

    drafts = []
    for i in range(body.count):
        topic = (body.topic_hints[i] if body.topic_hints and i < len(body.topic_hints) else None)
        draft = SocialContentDraft(
            id=_uuid.uuid4(),
            tenant_id=_uuid.UUID(body.tenant_id),
            text_content=f"[Admin generated] Draft {i + 1}" + (f" about {topic}" if topic else ""),
            ai_notes=f"Force-generated by admin. Model: {_ai_config['model']}",
            status="PENDING",
        )
        db.add(draft)
        drafts.append(str(draft.id))

    await db.commit()
    return {"ok": True, "tenant_id": body.tenant_id, "draft_ids": drafts}


@router.get("/tenant-overview")
async def tenant_overview(
    _: SuperAdmin,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Overview of all tenants' AI Social usage."""
    drafts_by_status = (
        await db.execute(
            select(SocialContentDraft.status, func.count().label("count"))
            .group_by(SocialContentDraft.status)
        )
    ).all()

    pending_approvals = (
        await db.execute(
            select(func.count()).select_from(SocialApprovalQueue).where(
                SocialApprovalQueue.response_received == False  # noqa: E712
            )
        )
    ).scalar_one()

    scheduled_posts = (
        await db.execute(
            select(func.count()).select_from(SocialScheduleQueue).where(
                SocialScheduleQueue.posted_status == "SCHEDULED"
            )
        )
    ).scalar_one()

    published_posts = (
        await db.execute(
            select(func.count()).select_from(SocialScheduleQueue).where(
                SocialScheduleQueue.posted_status == "PUBLISHED"
            )
        )
    ).scalar_one()

    return {
        "drafts_by_status": {row.status: row.count for row in drafts_by_status},
        "pending_approvals": pending_approvals,
        "scheduled_posts": scheduled_posts,
        "published_posts": published_posts,
        "ai_config": _ai_config,
    }


# ── Read endpoints powering the Step 4 admin pages ────────────────────────


@router.get("/ai-config")
async def get_ai_config(_: SuperAdmin) -> dict[str, Any]:
    """Return the current global AI Social config."""
    return {"config": _ai_config}


@router.get("/tenants-list")
async def tenants_with_social_activity(
    _: SuperAdmin,
    db: AsyncSession = Depends(get_db),
) -> list[dict[str, Any]]:
    """Tenants list for the manual-regeneration picker, with per-tenant draft counts."""
    rows = (
        await db.execute(
            select(
                Tenant.id,
                Tenant.name,
                func.count(SocialContentDraft.id).label("draft_count"),
            )
            .outerjoin(SocialContentDraft, SocialContentDraft.tenant_id == Tenant.id)
            .group_by(Tenant.id, Tenant.name)
            .order_by(Tenant.name)
        )
    ).all()
    return [
        {"id": str(r.id), "name": r.name, "draft_count": r.draft_count}
        for r in rows
    ]


@router.get("/scheduler")
async def scheduler_status(
    _: SuperAdmin,
    db: AsyncSession = Depends(get_db),
    limit: int = Query(100, le=500),
) -> dict[str, Any]:
    """Scheduler queue status — counts by status + the next 100 scheduled items."""
    counts = (
        await db.execute(
            select(SocialScheduleQueue.posted_status, func.count().label("count"))
            .group_by(SocialScheduleQueue.posted_status)
        )
    ).all()

    now = datetime.now(timezone.utc)
    overdue = (
        await db.execute(
            select(func.count())
            .select_from(SocialScheduleQueue)
            .where(
                SocialScheduleQueue.posted_status == "SCHEDULED",
                SocialScheduleQueue.scheduled_time != None,  # noqa: E711
                SocialScheduleQueue.scheduled_time <= now,
            )
        )
    ).scalar_one()

    items = (
        await db.execute(
            select(
                SocialScheduleQueue.id,
                SocialScheduleQueue.tenant_id,
                SocialScheduleQueue.draft_id,
                SocialScheduleQueue.platform,
                SocialScheduleQueue.scheduled_time,
                SocialScheduleQueue.posted_status,
                Tenant.name.label("tenant_name"),
            )
            .outerjoin(Tenant, Tenant.id == SocialScheduleQueue.tenant_id)
            .order_by(SocialScheduleQueue.scheduled_time.asc().nullsfirst())
            .limit(limit)
        )
    ).all()

    return {
        "counts_by_status": {row.posted_status or "UNKNOWN": row.count for row in counts},
        "overdue": overdue,
        "items": [
            {
                "id": str(r.id),
                "tenant_id": str(r.tenant_id),
                "tenant_name": r.tenant_name,
                "draft_id": str(r.draft_id),
                "platform": r.platform,
                "scheduled_time": r.scheduled_time.isoformat() if r.scheduled_time else None,
                "posted_status": r.posted_status,
            }
            for r in items
        ],
    }


@router.get("/failures")
async def failure_logs(
    _: SuperAdmin,
    db: AsyncSession = Depends(get_db),
    limit: int = Query(200, le=500),
) -> dict[str, Any]:
    """List all failed schedule entries + drafts stuck in REVISE.

    Failures include:
      * SocialScheduleQueue with posted_status='ERROR'
      * SocialContentDraft with status='REVISE'
    """
    failed_schedule = (
        await db.execute(
            select(
                SocialScheduleQueue.id,
                SocialScheduleQueue.tenant_id,
                SocialScheduleQueue.draft_id,
                SocialScheduleQueue.platform,
                SocialScheduleQueue.scheduled_time,
                Tenant.name.label("tenant_name"),
            )
            .outerjoin(Tenant, Tenant.id == SocialScheduleQueue.tenant_id)
            .where(SocialScheduleQueue.posted_status == "ERROR")
            .limit(limit)
        )
    ).all()

    revise_drafts = (
        await db.execute(
            select(
                SocialContentDraft.id,
                SocialContentDraft.tenant_id,
                SocialContentDraft.text_content,
                SocialContentDraft.ai_notes,
                SocialContentDraft.created_at,
                Tenant.name.label("tenant_name"),
            )
            .outerjoin(Tenant, Tenant.id == SocialContentDraft.tenant_id)
            .where(SocialContentDraft.status == "REVISE")
            .order_by(SocialContentDraft.created_at.desc())
            .limit(limit)
        )
    ).all()

    return {
        "publish_errors": [
            {
                "id": str(r.id),
                "tenant_id": str(r.tenant_id),
                "tenant_name": r.tenant_name,
                "draft_id": str(r.draft_id),
                "platform": r.platform,
                "scheduled_time": r.scheduled_time.isoformat() if r.scheduled_time else None,
            }
            for r in failed_schedule
        ],
        "revision_requests": [
            {
                "draft_id": str(r.id),
                "tenant_id": str(r.tenant_id),
                "tenant_name": r.tenant_name,
                "text_content": (r.text_content or "")[:240],
                "ai_notes": (r.ai_notes or "")[:240],
                "created_at": r.created_at.isoformat() if r.created_at else None,
            }
            for r in revise_drafts
        ],
    }


@router.get("/insights")
async def tenant_insights(
    _: SuperAdmin,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Per-tenant insights: drafts/approvals/scheduled/published counts."""
    rows = (
        await db.execute(
            select(
                Tenant.id,
                Tenant.name,
                func.count(SocialContentDraft.id).label("draft_count"),
            )
            .outerjoin(SocialContentDraft, SocialContentDraft.tenant_id == Tenant.id)
            .group_by(Tenant.id, Tenant.name)
        )
    ).all()

    approval_counts_q = (
        await db.execute(
            select(SocialApprovalQueue.tenant_id, func.count().label("count"))
            .group_by(SocialApprovalQueue.tenant_id)
        )
    ).all()
    approval_counts = {str(r.tenant_id): r.count for r in approval_counts_q}

    sched_q = (
        await db.execute(
            select(
                SocialScheduleQueue.tenant_id,
                SocialScheduleQueue.posted_status,
                func.count().label("count"),
            )
            .group_by(SocialScheduleQueue.tenant_id, SocialScheduleQueue.posted_status)
        )
    ).all()
    sched_counts: dict[str, dict[str, int]] = {}
    for r in sched_q:
        sched_counts.setdefault(str(r.tenant_id), {})[r.posted_status or "UNKNOWN"] = r.count

    return {
        "tenants": [
            {
                "id": str(r.id),
                "name": r.name,
                "drafts": r.draft_count,
                "approvals_sent": approval_counts.get(str(r.id), 0),
                "scheduled": sched_counts.get(str(r.id), {}).get("SCHEDULED", 0),
                "published": sched_counts.get(str(r.id), {}).get("PUBLISHED", 0),
                "errors": sched_counts.get(str(r.id), {}).get("ERROR", 0),
            }
            for r in rows
        ]
    }
